name: Check if comptaible to commit for the pr
on:
  pull_request:
    paths:
      - "fb0/*.json"
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Accessing The Code
      uses: actions/checkout@v2

    - name: Checkup if available the pr
      run: |
        bash test.sh check_pr
