name: Move and Push the Content

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up env
      env:
        discord: ${{ secrets.DISCORD }}

    - name: Access The Code
      uses: actions/checkout@v2

    - name: Update Submodule
      run: |
        git submodule update --init --recursive

    - name: Execute the test
      run: |
        bash test.sh push

    - name: Submit the 
      run: |
        git add -A
        git commit -m "Auto update"
        git push