name: Move and Push the Content

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access The Code
      uses: actions/checkout@v2
    
    - name: Update Submodule
      run: |
        git submodule update --init --recursive

    - name: Push
      run: |
        export discord="${{ secrets.DISCORD }}"
        bash test.sh push

    - name: Submit the ctx
      run: |
        git add -A
        git commit -m "Auto update"
        git push